package com.guncat.ecommerce.product.enums;

import lombok.Getter;

@Getter
public enum ProdKind {
    SWEATSHIRT("맨투맨 / 스웨트"),
    SHIRTS("셔츠 / 블라우스"),
    TOP_HOODIE("후드 티셔츠"),
    SWEATER("니트 / 스웨터"),
    COLLAR("카라 티셔츠"),
    LONG_SLEEVE("긴소매 티셔츠"),
    HALF_SLEEVE("반소매 티셔츠"),
    ETC_TOP("기타 상의"),
    DENIM_PANTS("데님 팬츠"),
    COTTON_PANTS("코튼 팬츠"),
    CASUAL_PANTS("슈트 팬츠 / 슬랙스"),
    JOGGER_PANTS("조거 팬츠"),
    SHORT_PANTS("숏 팬츠"),
    LEGGINGS("레깅스"),
    JUMP_SUIT("점프 슈트 / 오버울"),
    ETC_PANTS("기타 바지"),
    MINI_ONE("미니원피스"),
    MED_ONE("미디원피스"),
    MAX_ONE("맥시원피스"),
    MINI_SKRT("미니스커트"),
    MED_SKRT("미디스커트"),
    LONG_SKRT("롱스커트"),
    OUTER_HOODIE("후드 집업"),
    BLOUSON("블루종 / MA-1"),
    LEATHER("레더 / 라이더스 재킷"),
    MUSTANG("무스탕 / 퍼"),
    TRUCKER("트러커 재킷"),
    SUIT("슈트 / 블레이저 재킷"),
    CARDIGAN("카디건"),
    ANORAK("아노락 재킷"),
    FLEECE("플리스 / 뽀글이"),
    STADIUM("스타디움 재킷"),
    ATMN_COAT("환절기 코트"),
    WIN_SIN_COAT("겨울 싱글 코트"),
    WIN_DUB_COAT("겨울 더블 코트"),
    WIN_ETC_COAT("겨울 기타 코트"),
    LONG_PADDED("롱패딩 / 헤비 아우터"),
    SHORT_PADDED("숏패딩 / 헤비 아우터"),
    PADDED_VEST("패딩 베스트"),
    VEST("베스트"),
    HUNTING("사파리 / 헌팅 재킷"),
    NYLON("나일론 / 코치 재킷"),
    ETC_OUTER("기타 아우터"),
    TRN_TOP("상의"),
    TRN_BTM("하의"),
    TRN_ONE("원피스"),
    TRN_SKRT("스커트"),
    TRN_OUTER("아우터"),
    TRN_SET("상하의 세트"),
    SWIM("수영복 / 비치웨어"),
    SPT_SHOES("스포츠신발"),
    SPT_BAG("스포츠가방"),
    SPT_CAP("스포츠모자"),
    RING("반지"),
    BRACELET("팔찌"),
    NECKLACE("목걸이"),
    EAR_RING("귀걸이"),
    SNEAKERS("스니커즈"),
    FORMAL("구두"),
    SLIPPER("샌들 / 슬리퍼"),
    BOOTS("부츠 / 워커"),
    SHOE_ITEM("신발 용품"),
    BACKPACK("백팩"),
    CROSS("메신저 / 크로스 백"),
    SHOULDER("숄더백"),
    TOTE("토트백"),
    REUSABLE("에코백"),
    DUFFEL("보스턴 / 더플백"),
    WAIST("웨이스트 백"),
    POUCH("파우치 백"),
    BRIFF("브리프 케이스"),
    SUITCASE("캐리어"),
    BAG_ITEM("가방 소품"),
    WALLET("지갑 / 머니클립"),
    CLUTCH("클러치 백"),
    HAT("모자"),
    SOCKS("양말 / 레그웨어"),
    GLASSES("선글라스 / 안경테"),
    BELT("벨트"),
    WATCH("시계"),
    ETC_ITEM("기타 패션소품"),
    INN_TOP("여성 속옷 상의"),
    INN_BTM("여성 속옷 하의"),
    INN_SET("여성 속옷 세트"),
    HOMEWEAR("홈웨어");

    private final String name;

    ProdKind(String name) {
        this.name = name;
    }
}
